trigger:
  branches:
    include:
    - sit
  paths:
    include:
    - 'api/**'
    exclude:
    - '*.md'

variables:
  group: testVariableGroup

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Satge 1
  jobs:
  - job: Job 1
    steps:
    - script: |
        echo "df -kh"
      displayName: 'Execting Job 1'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerHubConnection'
        repository: 'kumar-m97/edge-micro'
        command: 'buildAndPush'
        tags: |
          $(Build.SourceVersionMessage)
        Dockerfile: './Docker-Image-Push/Dockerfile'
      displaName: 'Pushing Docker Image'

- stage: Stage 2
  dependsON: Stage 1
  jobs:
  - job: Stage 2 - Job1
    steps:
    - task: Maven@4
      inputs:
        mavenPOMFile: 'pom.xml'
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
      displayName: "Maven Packaging"







